build:
  main: src/main.rs
  binary: appa
  goos:
    - darwin
    - linux
    - windows
    - freebsd
    - netbsd
    - openbsd
  goarch:
    - amd64
    - 386
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^refactor'
scoop:
  commit_author:
    name: guidiego
    email: guidiego.expgames@gmail.com