[package]

name = "appa"
version = "0.0.1"
authors = [
    "Guilherme Diego <guilherme.albino.francisco@gmail.com>",
    "Mateus Freira <mateus@tenfold.com>"
]

[dependencies]
yaml-rust = "0.4"
serde_json = "1.0"
rayon = "1.0"